CREATE TABLE IF NOT EXISTS Screens (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    status VARCHAR(50) DEFAULT 'offline',
    lastPing DATETIME,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE Schedules ADD COLUMN screenId INT;
ALTER TABLE Schedules ADD FOREIGN KEY (screenId) REFERENCES Screens(id) ON DELETE CASCADE;

